### ISSUE TITLE
Make Zopim chat directive

### ISSUE THREAD

**Issue by slickrick1983** [legalthings/feedback#21]
We want to be able to chat with customers in the frontend. PLease integrate zopim chat function.

**Comment by Sarfaraaz** [comment]
Weren't we going to use Intercom instead?

**Comment by slickrick1983** [comment]
Klopt. Je kan deze account details gebruiken
https://app.intercom.io/admins/sign_in 

martijn@firm24.com
7e@NM4mJH3%9
