### ISSUE TITLE
Signing field is also visible at the first page while placed at the last page

### ISSUE THREAD

**Issue by YoLode** [legalthings/feedback#22]
The signing field is also visible at the first page of a document while it was placed on the last page. For me it happend with the 'Algemene voorwaarden' documents.

![image](https://cloud.githubusercontent.com/assets/11313258/8822202/0199e7b6-3064-11e5-9b99-44aa7b6a81e5.png)

![image](https://cloud.githubusercontent.com/assets/11313258/8822224/280feb2a-3064-11e5-80ad-1a596af24737.png)

**Comment by Sarfaraaz** [comment]
Tested multiple times and I cannot reproduce this. If this issue is still present, please reopen the issue.
