### ISSUE TITLE
Selecting contracts from Dashboard does not work

### ISSUE THREAD

**Issue by masterbrowser** [legalthings/feedback#24]

**Comment by masterbrowser** [comment]
this still does not work for me on firm24.docarama.com
is your pull request accepted, or should I or @jasny do something?

**Comment by moesjarraf** [comment]
@masterbrowser Works for me on firm24.docarama.com. Please test again and close the issue if its fixed for you.
![dashboard](https://cloud.githubusercontent.com/assets/5793511/9006245/76b1005c-3785-11e5-8628-800ec04bac1f.png)
