### ISSUE TITLE
Font color selected menu item 

### ISSUE THREAD

**Issue by masterbrowser** [legalthings/feedback#27]
firm24.docarama.com

In the top menu bar, text is not readible as it is white on white -> see screenshot.
Please make font color dark like when you hover -> see screenshot 2
![screen shot 2015-07-31 at 09 38 54](https://cloud.githubusercontent.com/assets/8112173/9002797/7d336ab8-3768-11e5-8f51-d44d77bf9d74.png)
![screen shot 2015-07-31 at 09 42 26](https://cloud.githubusercontent.com/assets/8112173/9002798/7d345342-3768-11e5-9832-95db5f02d115.png)

**Comment by slickrick1983** [comment]
@jurrew27 have you commited this and send me a PR? Seems like you did this looking at the label DONE

**Comment by jurrew27** [comment]
Geen pull request, maar het is inderdaad al wel gedaan en het staat ook al
goed op staging.

Op vr 14 aug. 2015 om 14:11 schreef slickrick1983 <notifications@github.com
