### ISSUE TITLE
My Organization is not visible

### ISSUE THREAD

**Issue by masterbrowser** [legalthings/feedback#37]
<img width="545" alt="screen shot 2015-07-31 at 20 36 03" src="https://cloud.githubusercontent.com/assets/8112173/9014615/cafe497e-37c3-11e5-9a7f-9700d457155c.png">

**Comment by slickrick1983** [comment]
@moesjarraf it should be pretty simple as the URL to our-organization is working
https://docs.firm24.com/our-organization
