### ISSUE TITLE
Make test user story for versioning en compare

### ISSUE THREAD

**Issue by slickrick1983** [legalthings/feedback#46]
A userstory should be made for editing a document, going to a new version, canceling a signing process, new version, then compare versions, and then finalyse

**Comment by masterbrowser** [comment]
https://docs.google.com/a/onlineflexbv.nl/spreadsheets/d/19d-wbq97GmtHjqDIebKhi0aGRCfsHwxFgKcz6TomhJ0/edit?usp=sharing
