### ISSUE TITLE
When signing a document for the second time the first signature is already in the txt

### ISSUE THREAD

**Issue by jasny** [legalthings/feedback#5]
![image](https://cloud.githubusercontent.com/assets/11313258/7613619/002c1592-f992-11e4-9a0e-583711819cf1.png)

---
Moved from legalthings/zzpmodelcontracten-registration#11
/cc @YoLode @yolode

**Comment by moesjarraf** [comment]
@YoLode 
How did you get to sign a fully finalized document for the second time? Once all signatures are placed you cannot modify a document anymore.

Please correct me if I misunderstood the issue.
