### ISSUE TITLE
Can't use the whole signing area, only the left side

### ISSUE THREAD

**Issue by YoLode** [legalthings/feedback#51]
![image](https://cloud.githubusercontent.com/assets/11313258/9169540/171ae78c-3f5c-11e5-92cd-fc81109ce5ec.png)

**Comment by slickrick1983** [comment]
@YoLode which browser en system? Window? Chrome?

**Comment by YoLode** [comment]
chrome

**Comment by moesjarraf** [comment]
I had this problem too, but it seems to be working fine for me now. I can´t find a commit that fixed this though. @YoLode could you test if this issue still occurs for you?

**Comment by moesjarraf** [comment]
Actually I noticed that this issue only occurs in the firm24 theme (zpp works fine), will look into it.

**Comment by Sarfaraaz** [comment]
Just tested and it seems to be working fine now.
