### ISSUE TITLE
Signing is not possible after selecting the option to sign a document at a later time ("later ondertekenen")

### ISSUE THREAD

**Issue by YoLode** [legalthings/feedback#54]
![image](https://cloud.githubusercontent.com/assets/11313258/9197500/f8cdea34-4034-11e5-9d14-04f385c93515.png)

**Comment by moesjarraf** [comment]
I can click on 'Sign later' and then go back to the signing-url whenever I want, which allows me to sign the document again. I am not sure what the problem is here? Could you elaborate @YoLode?

**Comment by slickrick1983** [comment]
Seems to work on staging
