### ISSUE TITLE
Saved signing parties cannot be removed from the document

### ISSUE THREAD

**Issue by moesjarraf** [legalthings/feedback#57]
Say you made a typo in a party's email, saved it, and now want to delete the party.
If you click on the `X` and then click `Next`, the party will still be there.

![naamloos](https://cloud.githubusercontent.com/assets/5793511/9335410/21f91d8a-45d4-11e5-849a-d45438f3c479.png)

This is due to the way DMS handles the `signatures` metadata. The DMS `updates the signatures by email`, rather than `replacing the entire signatures metadata`. I suggest we make a POST request like so to delete signature parties:

    [POST] /documents/abcdefghikjklmnopqrstuvwxyz123456

    "signatures" : {
        "parties" : [ 
            {
                "email" : "developer@legalthings.net",
                "deleted": true
            }
        ]
    }

@jasny Do you agree or should I handle this differently.

**Comment by jasny** [comment]
The suggested solution sounds good. Lets name the field `deleted` rather than `delete`.
