### ISSUE TITLE
If you left the signing page as a user, you can't go back easily

### ISSUE THREAD

**Issue by moesjarraf** [legalthings/feedback#58]
If you left the signing page as a user, you can't go back easily by clicking on some button. There should be an indicator on which you can click that redirects you to the signing page. (if of course you have yet to sign)

![clickable](https://cloud.githubusercontent.com/assets/5793511/9351072/74babff6-4656-11e5-9f65-9d74fa377846.png)

**Comment by jasny** [comment]
There should be a **'Sign document' button** when you should sign. This button probably got lost during merge between master and zzpmodelcontracten.

**Comment by moesjarraf** [comment]
Yeah, that button wasn't showing up because the variable that determines it's condition was unreachable from the controller it was in. I moved it up a scope and renamed it.
