### ISSUE TITLE
Converting PDF to PNG sometimes fails

### ISSUE THREAD

**Issue by jasny** [legalthings/feedback#6]
Often converting one or two of the pages of a large document fails. This causes them to be missing it the signing process.

**Comment by moesjarraf** [comment]
@jasny Do we still need to investigate further into this issue? Because implementing PDF.js would solve the problem.

**Comment by jasny** [comment]
This will be solved by [pdf.js](https://github.com/legalthings/feedback/wiki/WL-PDFjs) and [conversion by Lambda](https://github.com/legalthings/feedback/wiki/WL-Convert-PDF-Images).
