### ISSUE TITLE
When signing, first page of the document is 'hidden'

### ISSUE THREAD

**Issue by moesjarraf** [legalthings/feedback#60]
Lately, quite often, the first page of the document retains the class `hide` even though it has been loaded correctly. Deleting this class through your browser-inspector shows that the page has loaded correctly.

![img-loaded](https://cloud.githubusercontent.com/assets/5793511/9358770/1a661374-468e-11e5-80d7-adccc7ce4882.png)

I am not sure why, but the `imgLoadedEvents` does not fire correctly for that first page (even though it has loaded).

**Comment by jasny** [comment]
Will be replace pdf.js
