### ISSUE TITLE
Place holder in signatures is really off

### ISSUE THREAD

**Issue by slickrick1983** [legalthings/feedback#73]
We really should have another look at signature possitioning. Signatures are all over the place when you use a tablet kind of laptop like mine. As all laptops are kind of tablets we should fix this!
![image](https://cloud.githubusercontent.com/assets/8124767/9654834/8c96493c-522d-11e5-972a-e91eb988ee03.png)

**Comment by Sarfaraaz** [comment]
Should be fixed with the recent changes to DocTools and DMS.
