### ISSUE TITLE
Remove icon and tooltip in front of documents

### ISSUE THREAD

**Issue by masterbrowser** [legalthings/feedback#76]
Dont understand what the use of this is

![screen shot 2015-09-07 at 16 23 31](https://cloud.githubusercontent.com/assets/8112173/9718561/39fe50c2-557d-11e5-8b65-bf06ca1e2943.png)

**Comment by Scoudem** [comment]
That is an overflow menu which is used for quick actions like renaming and
tagging. I think thats pretty useful?
Op 7 sep. 2015 16:27 schreef "masterbrowser" <notifications@github.com>:

**Comment by masterbrowser** [comment]
I think its only useful when we have tumbnail views.
