### ISSUE TITLE
Res1280 x 720 awesome signature really far off 

### ISSUE THREAD

**Issue by slickrick1983** [legalthings/feedback#88]
Res: 1280 x 720 (my tablet PC) placing signatures  boxes are not in the place where I draged them.
When I susequnetly finalise the doc it get placed in the middle of the text of the doc. See screen

![image](https://cloud.githubusercontent.com/assets/8124767/10025236/8818dafe-615b-11e5-841f-f1b9f8cd86ba.png)

**Comment by Sarfaraaz** [comment]
This is probably a Doctools or PDFTools issue. The resolution shouldn't matter.

The signature box is in fact at the correct position, but the markup of the document itself differs quite a bit (more spacing, different margins for different elements, etc) which makes things like this happen. 
Different documents will produce different output so this might be more noticeable in certain documents than others. It'd be real nice if both systems generated the same markup.

Also this issue has been brought forward multiple times in multiple issues such as #73. Duplicates should be closed.

**Comment by Sarfaraaz** [comment]
Should be fixed with the recent changes to DocTools and DMS.
