### ISSUE TITLE
ZZPmodelcontracten - code is visible on frontend

### ISSUE THREAD

**Issue by masterbrowser** [legalthings/feedback#89]
On the dashboard of ZZPmodelcontracten, if you click the button "Hoe werkt het" there is code visible.
Please solve.

![screen shot 2015-09-23 at 09 05 29](https://cloud.githubusercontent.com/assets/8112173/10041300/9af39a6e-61e3-11e5-8002-0c075dbd4914.png)

**Comment by masterbrowser** [comment]
still visible for me

**Comment by Sarfaraaz** [comment]
It's fixed on [staging](http://zzpmodelcontracten.docarama.com/dashboard) and it's probably not yet deployed to live.
