### ISSUE TITLE
ZZPmodelcontracten frontend is broken

### ISSUE THREAD

**Issue by masterbrowser** [legalthings/feedback#96]
<img width="463" alt="screen shot 2015-10-04 at 13 03 58" src="https://cloud.githubusercontent.com/assets/8112173/10267536/9c6b5f9a-6a98-11e5-8371-7064c11e411b.png">

**Comment by Sarfaraaz** [comment]
Works fine on my end. It's probably a connection issue on your end.

**Comment by Sarfaraaz** [comment]
You're going to zppmodelcontracten. It's z**z**pmodelcontracten. :smile:

**Comment by masterbrowser** [comment]
Oeps - sorry!!
